name: audio_monitor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_acrcloud:
    path: ./flutter_acrcloud/
  flutter_redux: ^0.10.0
  permission_handler: ^11.0.1
  redux: ^5.0.0
  workmanager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/FuturaBookfont.ttf
          weight: 400
        - asset: assets/fonts/futuramediumbt.ttf
          weight: 500
        - asset: assets/fonts/futur.ttf
          weight: 700
        - asset: assets/fonts/FuturaExtraBlackfont.ttf
          weight: 900
